import { useEffect, useMemo, useState } from "react";
import { applyVaultSkin, deleteVaultSkin, getCurrentSkinUrl, listSkinVault, openSkinVaultFolder, resetSkin, saveSkinToVault, setSkinUrl } from "../api/skin.js";
import SkinMirror from "./SkinMirror.jsx";

export function SkinChangerContent() {
  const [currentUrl, setCurrentUrl] = useState(null); const [vault, setVault] = useState([]); const [selectedId, setSelectedId] = useState(null); const [variant, setVariant] = useState("classic"); const [skinName, setSkinName] = useState(""); const [urlInput, setUrlInput] = useState(""); const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(null); const [message, setMessage] = useState(null);
  async function refresh() { const entries = await listSkinVault(); setVault(entries); setSelectedId((current) => entries.some((entry) => entry.id === current) ? current : entries[0]?.id ?? null); getCurrentSkinUrl().then(setCurrentUrl).catch((err) => setError(err?.message ?? String(err))); }
  useEffect(() => { refresh().catch((err) => setError(err?.message ?? String(err))); }, []);
  async function runAction(fn, successMessage, reload = true) { setBusy(true); setError(null); setMessage(null); try { await fn(); setMessage(successMessage); if (reload) await refresh(); } catch (err) { setError(err?.message ?? String(err)); } finally { setBusy(false); } }
  async function importSkin(event) { const file = event.target.files?.[0]; if (!file) return; await runAction(() => saveSkinToVault(file, skinName || file.name.replace(/\.png$/i, ""), variant), "Skin in der Schmiede bewahrt."); setSkinName(""); event.target.value = ""; }
  async function removeSelected() { const selected = vault.find((entry) => entry.id === selectedId); if (!selected || !window.confirm(`„${selected.name}“ wirklich aus der lokalen Schmiede entfernen?`)) return; await runAction(() => deleteVaultSkin(selected.id), "Skin aus der Schmiede entfernt."); }
  const filtered = useMemo(() => vault.filter((entry) => entry.name.toLowerCase().includes(query.trim().toLowerCase())), [vault, query]); const selected = vault.find((entry) => entry.id === selectedId);
  return <div className="erzmark-skin-forge">
    <aside className="erzmark-skin-forge-stage"><div className="erzmark-skin-forge-runes" aria-hidden="true">ᛖ · ᚱ · ᛉ</div><div className="erzmark-skin-forge-live"><i />Animationsspiegel aktiv</div><SkinMirror skinUrl={selected?.previewDataUrl ?? currentUrl} lively width={300} height={380} /><div className="erzmark-skin-forge-identity"><small>{selected ? "Aus der Skin-Schmiede" : "Aktiver Minecraft-Skin"}</small><strong>{selected?.name ?? "Deine Gestalt"}</strong><span>{selected?.variant === "slim" ? "Schmales Modell" : "Klassisches Modell"} · bewegen, drehen, doppelklicken</span></div>{selected && <div className="erzmark-skin-forge-stage-actions"><button onClick={() => runAction(() => applyVaultSkin(selected.id), `„${selected.name}“ ist jetzt dein Minecraft-Skin.`)} disabled={busy}>Skin tragen</button><button onClick={removeSelected} disabled={busy}>Entfernen</button></div>}</aside>
    <main className="erzmark-skin-forge-library"><header className="erzmark-settings-section-heading"><span className="erzmark-settings-kicker">Lokale Sammlung</span><h3>Skin-Schmiede</h3><p>Bewahre mehrere Gestalten lokal auf und übertrage nur die ausgewählte zu Minecraft.</p></header>
      <div className="erzmark-skin-forge-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Schmiede durchsuchen…" /><button onClick={openSkinVaultFolder}>Ordner ↗</button></div>
      <div className="erzmark-skin-vault-grid">{filtered.map((entry) => <button key={entry.id} className={entry.id === selectedId ? "is-active" : ""} onClick={() => setSelectedId(entry.id)}><span>{entry.previewDataUrl ? <img src={entry.previewDataUrl} alt="" /> : "◇"}</span><b>{entry.name}</b><small>{entry.variant === "slim" ? "Slim" : "Classic"}</small></button>)}<label className="erzmark-skin-vault-add"><span>＋</span><b>Skin hinzufügen</b><small>PNG · 64×64 oder 64×32</small><input type="file" accept="image/png" onChange={importSkin} disabled={busy} hidden /></label></div>
      <section className="erzmark-skin-forge-import"><div><label>Name der Gestalt<input value={skinName} maxLength={40} onChange={(event) => setSkinName(event.target.value)} placeholder="z. B. Nachtwächter" /></label><fieldset><legend>Modell</legend><button className={variant === "classic" ? "is-active" : ""} onClick={() => setVariant("classic")}>Classic</button><button className={variant === "slim" ? "is-active" : ""} onClick={() => setVariant("slim")}>Slim</button></fieldset></div><p>Der Name und das Skin-Bild bleiben lokal auf diesem Gerät. Erst „Skin tragen“ sendet die PNG über Mojangs offizielle API.</p></section>
      <details className="erzmark-skin-forge-advanced"><summary>Weitere Minecraft-Aktionen</summary><div><input type="url" placeholder="Skin-URL https://…" value={urlInput} onChange={(event) => setUrlInput(event.target.value)} /><button onClick={() => runAction(() => setSkinUrl(variant, urlInput.trim()), "Skin von URL übernommen.")} disabled={busy || !urlInput.trim()}>URL anwenden</button><button className="is-danger" onClick={() => runAction(resetSkin, "Minecraft-Skin zurückgesetzt.")} disabled={busy}>Skin zurücksetzen</button></div></details>
      {message && <p className="erzmark-hint">{message}</p>}{error && <p className="erzmark-error">{error}</p>}
    </main>
  </div>;
}

export default function SkinChangerScreen({ onClose }) { return <div className="erzmark-modal-backdrop" onClick={onClose}><div className="erzmark-modal-panel erzmark-modal-panel-wide" onClick={(event) => event.stopPropagation()}><div className="erzmark-modal-header"><h2>Skin-Schmiede</h2><button className="erzmark-modal-close" onClick={onClose} aria-label="Schließen">✕</button></div><div className="erzmark-modal-body"><SkinChangerContent /></div></div></div>; }
